version: "3.7"
   
services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:9000"      
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    container_name: django_tgbot

  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python manage.py bot" 
    volumes:
      - .:/code
    container_name: djbot

volumes:
  postgres_data:
  media_volume:
  static_volume: